# master-deployment.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: master-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: master
  template:
    metadata:
      labels:
        app: master
    spec:
      containers:
        - name: master
          image: pes2ug21cs914/ver2-master:latest

          ports:
          - containerPort: 5001
          env:
          - name: MONGO_HOST
            value: mongodb-service
          - name: MONGO_PORT
            value: "27017"
          - name: FLASK_ENV
            value: "production"
---
apiVersion: v1
kind: Service
metadata:
  name: master-service
spec:
  type: LoadBalancer
  selector:
    app: master
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5001
