# orders-deployment.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: orders
  template:
    metadata:
      labels:
        app: orders
    spec:
      containers:
        - name: orders
          image: pes2ug21cs914/ver2-orders:latest
          ports:
          - containerPort: 5005
          env:
          - name: MONGO_HOST
            value: mongodb-service
          - name: MONGO_PORT
            value: "27017"
          - name: FLASK_ENV
            value: "production"
---
apiVersion: v1
kind: Service
metadata:
  name: orders-service
spec:
  type: LoadBalancer
  selector:
    app: orders
  ports:
    - protocol: TCP
      port: 5005
      targetPort: 5005
