# products-deployment.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: products-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: products
  template:
    metadata:
      labels:
        app: products
    spec:
      containers:
        - name: products
          image: pes2ug21cs914/ver2-products:latest
          ports:
          - containerPort: 5002
          env:
          - name: MONGO_HOST
            value: mongodb-service
          - name: MONGO_PORT
            value: "27017"
          - name: FLASK_ENV
            value: "production"
---
apiVersion: v1
kind: Service
metadata:
  name: products-service
spec:
  type: LoadBalancer
  selector:
    app: products
  ports:
    - protocol: TCP
      port: 5002
      targetPort: 5002
