# users-deployment.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: users
  template:
    metadata:
      labels:
        app: users
    spec:
      containers:
        - name: users
          image: pes2ug21cs914/ver2-users:latest
          ports:
          - containerPort: 5004
          env:
          - name: MONGO_HOST
            value: mongodb-service
          - name: MONGO_PORT
            value: "27017"
          - name: FLASK_ENV
            value: "production"
---
apiVersion: v1
kind: Service
metadata:
  name: users-service
spec:
  type: LoadBalancer
  selector:
    app: users
  ports:
    - protocol: TCP
      port: 5004
      targetPort: 5004
      


